// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_tasks.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentTask = `-- name: CreateAgentTask :one
INSERT INTO agent_tasks (name, cron_expression, prompt, enabled, mcp_config, allowed_tools, system_agent, global_skill_access, on_success_task_id, on_failure_task_id, task_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'cron')
RETURNING id, name, cron_expression, prompt, enabled, created_at, updated_at, task_type, run_at, mcp_config, allowed_tools, system_agent, global_skill_access, on_success_task_id, on_failure_task_id
`

type CreateAgentTaskParams struct {
	Name              string      `json:"name"`
	CronExpression    pgtype.Text `json:"cron_expression"`
	Prompt            string      `json:"prompt"`
	Enabled           bool        `json:"enabled"`
	McpConfig         pgtype.Text `json:"mcp_config"`
	AllowedTools      pgtype.Text `json:"allowed_tools"`
	SystemAgent       bool        `json:"system_agent"`
	GlobalSkillAccess bool        `json:"global_skill_access"`
	OnSuccessTaskID   pgtype.UUID `json:"on_success_task_id"`
	OnFailureTaskID   pgtype.UUID `json:"on_failure_task_id"`
}

func (q *Queries) CreateAgentTask(ctx context.Context, arg CreateAgentTaskParams) (AgentTask, error) {
	row := q.db.QueryRow(ctx, createAgentTask,
		arg.Name,
		arg.CronExpression,
		arg.Prompt,
		arg.Enabled,
		arg.McpConfig,
		arg.AllowedTools,
		arg.SystemAgent,
		arg.GlobalSkillAccess,
		arg.OnSuccessTaskID,
		arg.OnFailureTaskID,
	)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CronExpression,
		&i.Prompt,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaskType,
		&i.RunAt,
		&i.McpConfig,
		&i.AllowedTools,
		&i.SystemAgent,
		&i.GlobalSkillAccess,
		&i.OnSuccessTaskID,
		&i.OnFailureTaskID,
	)
	return i, err
}

const createScheduledTask = `-- name: CreateScheduledTask :one
INSERT INTO agent_tasks (name, prompt, run_at, mcp_config, allowed_tools, system_agent, global_skill_access, task_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'one_time')
RETURNING id, name, cron_expression, prompt, enabled, created_at, updated_at, task_type, run_at, mcp_config, allowed_tools, system_agent, global_skill_access, on_success_task_id, on_failure_task_id
`

type CreateScheduledTaskParams struct {
	Name              string             `json:"name"`
	Prompt            string             `json:"prompt"`
	RunAt             pgtype.Timestamptz `json:"run_at"`
	McpConfig         pgtype.Text        `json:"mcp_config"`
	AllowedTools      pgtype.Text        `json:"allowed_tools"`
	SystemAgent       bool               `json:"system_agent"`
	GlobalSkillAccess bool               `json:"global_skill_access"`
}

func (q *Queries) CreateScheduledTask(ctx context.Context, arg CreateScheduledTaskParams) (AgentTask, error) {
	row := q.db.QueryRow(ctx, createScheduledTask,
		arg.Name,
		arg.Prompt,
		arg.RunAt,
		arg.McpConfig,
		arg.AllowedTools,
		arg.SystemAgent,
		arg.GlobalSkillAccess,
	)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CronExpression,
		&i.Prompt,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaskType,
		&i.RunAt,
		&i.McpConfig,
		&i.AllowedTools,
		&i.SystemAgent,
		&i.GlobalSkillAccess,
		&i.OnSuccessTaskID,
		&i.OnFailureTaskID,
	)
	return i, err
}

const deleteAgentTask = `-- name: DeleteAgentTask :exec
DELETE FROM agent_tasks WHERE id = $1
`

func (q *Queries) DeleteAgentTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgentTask, id)
	return err
}

const getAgentTask = `-- name: GetAgentTask :one
SELECT id, name, cron_expression, prompt, enabled, created_at, updated_at, task_type, run_at, mcp_config, allowed_tools, system_agent, global_skill_access, on_success_task_id, on_failure_task_id FROM agent_tasks WHERE id = $1
`

func (q *Queries) GetAgentTask(ctx context.Context, id uuid.UUID) (AgentTask, error) {
	row := q.db.QueryRow(ctx, getAgentTask, id)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CronExpression,
		&i.Prompt,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaskType,
		&i.RunAt,
		&i.McpConfig,
		&i.AllowedTools,
		&i.SystemAgent,
		&i.GlobalSkillAccess,
		&i.OnSuccessTaskID,
		&i.OnFailureTaskID,
	)
	return i, err
}

const listAgentTasks = `-- name: ListAgentTasks :many
SELECT id, name, cron_expression, prompt, enabled, created_at, updated_at, task_type, run_at, mcp_config, allowed_tools, system_agent, global_skill_access, on_success_task_id, on_failure_task_id FROM agent_tasks ORDER BY created_at DESC
`

func (q *Queries) ListAgentTasks(ctx context.Context) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listAgentTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CronExpression,
			&i.Prompt,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaskType,
			&i.RunAt,
			&i.McpConfig,
			&i.AllowedTools,
			&i.SystemAgent,
			&i.GlobalSkillAccess,
			&i.OnSuccessTaskID,
			&i.OnFailureTaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledCronTasks = `-- name: ListEnabledCronTasks :many
SELECT id, name, cron_expression, prompt, enabled, created_at, updated_at, task_type, run_at, mcp_config, allowed_tools, system_agent, global_skill_access, on_success_task_id, on_failure_task_id FROM agent_tasks
WHERE enabled = true AND task_type = 'cron'
ORDER BY created_at DESC
`

func (q *Queries) ListEnabledCronTasks(ctx context.Context) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listEnabledCronTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CronExpression,
			&i.Prompt,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaskType,
			&i.RunAt,
			&i.McpConfig,
			&i.AllowedTools,
			&i.SystemAgent,
			&i.GlobalSkillAccess,
			&i.OnSuccessTaskID,
			&i.OnFailureTaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingScheduledTasks = `-- name: ListPendingScheduledTasks :many
SELECT id, name, cron_expression, prompt, enabled, created_at, updated_at, task_type, run_at, mcp_config, allowed_tools, system_agent, global_skill_access, on_success_task_id, on_failure_task_id FROM agent_tasks
WHERE enabled = true AND task_type = 'one_time'
ORDER BY run_at ASC
`

func (q *Queries) ListPendingScheduledTasks(ctx context.Context) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listPendingScheduledTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CronExpression,
			&i.Prompt,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaskType,
			&i.RunAt,
			&i.McpConfig,
			&i.AllowedTools,
			&i.SystemAgent,
			&i.GlobalSkillAccess,
			&i.OnSuccessTaskID,
			&i.OnFailureTaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemAgentTasks = `-- name: ListSystemAgentTasks :many
SELECT id, name, cron_expression, prompt, enabled, created_at, updated_at, task_type, run_at, mcp_config, allowed_tools, system_agent, global_skill_access, on_success_task_id, on_failure_task_id FROM agent_tasks
WHERE system_agent = true
ORDER BY created_at DESC
`

func (q *Queries) ListSystemAgentTasks(ctx context.Context) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listSystemAgentTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CronExpression,
			&i.Prompt,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaskType,
			&i.RunAt,
			&i.McpConfig,
			&i.AllowedTools,
			&i.SystemAgent,
			&i.GlobalSkillAccess,
			&i.OnSuccessTaskID,
			&i.OnFailureTaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAgentTasks = `-- name: ListUserAgentTasks :many
SELECT id, name, cron_expression, prompt, enabled, created_at, updated_at, task_type, run_at, mcp_config, allowed_tools, system_agent, global_skill_access, on_success_task_id, on_failure_task_id FROM agent_tasks
WHERE system_agent = false
ORDER BY created_at DESC
`

func (q *Queries) ListUserAgentTasks(ctx context.Context) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listUserAgentTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CronExpression,
			&i.Prompt,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TaskType,
			&i.RunAt,
			&i.McpConfig,
			&i.AllowedTools,
			&i.SystemAgent,
			&i.GlobalSkillAccess,
			&i.OnSuccessTaskID,
			&i.OnFailureTaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentTask = `-- name: UpdateAgentTask :one
UPDATE agent_tasks
SET name = $2,
    cron_expression = $3,
    prompt = $4,
    enabled = $5,
    mcp_config = $6,
    allowed_tools = $7,
    system_agent = $8,
    global_skill_access = $9,
    on_success_task_id = $10,
    on_failure_task_id = $11,
    updated_at = now()
WHERE id = $1
RETURNING id, name, cron_expression, prompt, enabled, created_at, updated_at, task_type, run_at, mcp_config, allowed_tools, system_agent, global_skill_access, on_success_task_id, on_failure_task_id
`

type UpdateAgentTaskParams struct {
	ID                uuid.UUID   `json:"id"`
	Name              string      `json:"name"`
	CronExpression    pgtype.Text `json:"cron_expression"`
	Prompt            string      `json:"prompt"`
	Enabled           bool        `json:"enabled"`
	McpConfig         pgtype.Text `json:"mcp_config"`
	AllowedTools      pgtype.Text `json:"allowed_tools"`
	SystemAgent       bool        `json:"system_agent"`
	GlobalSkillAccess bool        `json:"global_skill_access"`
	OnSuccessTaskID   pgtype.UUID `json:"on_success_task_id"`
	OnFailureTaskID   pgtype.UUID `json:"on_failure_task_id"`
}

func (q *Queries) UpdateAgentTask(ctx context.Context, arg UpdateAgentTaskParams) (AgentTask, error) {
	row := q.db.QueryRow(ctx, updateAgentTask,
		arg.ID,
		arg.Name,
		arg.CronExpression,
		arg.Prompt,
		arg.Enabled,
		arg.McpConfig,
		arg.AllowedTools,
		arg.SystemAgent,
		arg.GlobalSkillAccess,
		arg.OnSuccessTaskID,
		arg.OnFailureTaskID,
	)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CronExpression,
		&i.Prompt,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TaskType,
		&i.RunAt,
		&i.McpConfig,
		&i.AllowedTools,
		&i.SystemAgent,
		&i.GlobalSkillAccess,
		&i.OnSuccessTaskID,
		&i.OnFailureTaskID,
	)
	return i, err
}
