// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_tasks.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createAgentTask = `-- name: CreateAgentTask :one
INSERT INTO agent_tasks (name, cron_expression, prompt, enabled, timeout_seconds)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, cron_expression, prompt, enabled, timeout_seconds, created_at, updated_at
`

type CreateAgentTaskParams struct {
	Name           string `json:"name"`
	CronExpression string `json:"cron_expression"`
	Prompt         string `json:"prompt"`
	Enabled        bool   `json:"enabled"`
	TimeoutSeconds int32  `json:"timeout_seconds"`
}

func (q *Queries) CreateAgentTask(ctx context.Context, arg CreateAgentTaskParams) (AgentTask, error) {
	row := q.db.QueryRow(ctx, createAgentTask,
		arg.Name,
		arg.CronExpression,
		arg.Prompt,
		arg.Enabled,
		arg.TimeoutSeconds,
	)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CronExpression,
		&i.Prompt,
		&i.Enabled,
		&i.TimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentTask = `-- name: DeleteAgentTask :exec
DELETE FROM agent_tasks WHERE id = $1
`

func (q *Queries) DeleteAgentTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgentTask, id)
	return err
}

const getAgentTask = `-- name: GetAgentTask :one
SELECT id, name, cron_expression, prompt, enabled, timeout_seconds, created_at, updated_at FROM agent_tasks WHERE id = $1
`

func (q *Queries) GetAgentTask(ctx context.Context, id uuid.UUID) (AgentTask, error) {
	row := q.db.QueryRow(ctx, getAgentTask, id)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CronExpression,
		&i.Prompt,
		&i.Enabled,
		&i.TimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentTasks = `-- name: ListAgentTasks :many
SELECT id, name, cron_expression, prompt, enabled, timeout_seconds, created_at, updated_at FROM agent_tasks ORDER BY created_at DESC
`

func (q *Queries) ListAgentTasks(ctx context.Context) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listAgentTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CronExpression,
			&i.Prompt,
			&i.Enabled,
			&i.TimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAgentTasks = `-- name: ListEnabledAgentTasks :many
SELECT id, name, cron_expression, prompt, enabled, timeout_seconds, created_at, updated_at FROM agent_tasks WHERE enabled = true ORDER BY created_at DESC
`

func (q *Queries) ListEnabledAgentTasks(ctx context.Context) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listEnabledAgentTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CronExpression,
			&i.Prompt,
			&i.Enabled,
			&i.TimeoutSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentTask = `-- name: UpdateAgentTask :one
UPDATE agent_tasks
SET name = $2,
    cron_expression = $3,
    prompt = $4,
    enabled = $5,
    timeout_seconds = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, name, cron_expression, prompt, enabled, timeout_seconds, created_at, updated_at
`

type UpdateAgentTaskParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	CronExpression string    `json:"cron_expression"`
	Prompt         string    `json:"prompt"`
	Enabled        bool      `json:"enabled"`
	TimeoutSeconds int32     `json:"timeout_seconds"`
}

func (q *Queries) UpdateAgentTask(ctx context.Context, arg UpdateAgentTaskParams) (AgentTask, error) {
	row := q.db.QueryRow(ctx, updateAgentTask,
		arg.ID,
		arg.Name,
		arg.CronExpression,
		arg.Prompt,
		arg.Enabled,
		arg.TimeoutSeconds,
	)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CronExpression,
		&i.Prompt,
		&i.Enabled,
		&i.TimeoutSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
