// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kanban_tasks.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createKanbanTask = `-- name: CreateKanbanTask :one
INSERT INTO kanban_tasks (title, description, agent_task_id)
VALUES ($1, $2, $3)
RETURNING id, title, description, agent_task_id, status, result, created_at, updated_at
`

type CreateKanbanTaskParams struct {
	Title       string    `json:"title"`
	Description string    `json:"description"`
	AgentTaskID uuid.UUID `json:"agent_task_id"`
}

func (q *Queries) CreateKanbanTask(ctx context.Context, arg CreateKanbanTaskParams) (KanbanTask, error) {
	row := q.db.QueryRow(ctx, createKanbanTask, arg.Title, arg.Description, arg.AgentTaskID)
	var i KanbanTask
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AgentTaskID,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKanbanTask = `-- name: DeleteKanbanTask :exec
DELETE FROM kanban_tasks WHERE id = $1
`

func (q *Queries) DeleteKanbanTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteKanbanTask, id)
	return err
}

const getKanbanTask = `-- name: GetKanbanTask :one
SELECT id, title, description, agent_task_id, status, result, created_at, updated_at FROM kanban_tasks WHERE id = $1
`

func (q *Queries) GetKanbanTask(ctx context.Context, id uuid.UUID) (KanbanTask, error) {
	row := q.db.QueryRow(ctx, getKanbanTask, id)
	var i KanbanTask
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AgentTaskID,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDistinctAgentsWithPendingKanbanTasks = `-- name: ListDistinctAgentsWithPendingKanbanTasks :many
SELECT DISTINCT agent_task_id FROM kanban_tasks
WHERE status IN ('todo', 'progress')
`

func (q *Queries) ListDistinctAgentsWithPendingKanbanTasks(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDistinctAgentsWithPendingKanbanTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var agent_task_id uuid.UUID
		if err := rows.Scan(&agent_task_id); err != nil {
			return nil, err
		}
		items = append(items, agent_task_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKanbanTasks = `-- name: ListKanbanTasks :many
SELECT id, title, description, agent_task_id, status, result, created_at, updated_at FROM kanban_tasks
ORDER BY created_at DESC
`

func (q *Queries) ListKanbanTasks(ctx context.Context) ([]KanbanTask, error) {
	rows, err := q.db.Query(ctx, listKanbanTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanTask{}
	for rows.Next() {
		var i KanbanTask
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.AgentTaskID,
			&i.Status,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKanbanTasksByAgentID = `-- name: ListKanbanTasksByAgentID :many
SELECT id, title, description, agent_task_id, status, result, created_at, updated_at FROM kanban_tasks
WHERE agent_task_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListKanbanTasksByAgentID(ctx context.Context, agentTaskID uuid.UUID) ([]KanbanTask, error) {
	rows, err := q.db.Query(ctx, listKanbanTasksByAgentID, agentTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanTask{}
	for rows.Next() {
		var i KanbanTask
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.AgentTaskID,
			&i.Status,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKanbanTasksByAgentIDAndStatus = `-- name: ListKanbanTasksByAgentIDAndStatus :many
SELECT id, title, description, agent_task_id, status, result, created_at, updated_at FROM kanban_tasks
WHERE agent_task_id = $1 AND status = $2
ORDER BY created_at DESC
`

type ListKanbanTasksByAgentIDAndStatusParams struct {
	AgentTaskID uuid.UUID        `json:"agent_task_id"`
	Status      KanbanTaskStatus `json:"status"`
}

func (q *Queries) ListKanbanTasksByAgentIDAndStatus(ctx context.Context, arg ListKanbanTasksByAgentIDAndStatusParams) ([]KanbanTask, error) {
	rows, err := q.db.Query(ctx, listKanbanTasksByAgentIDAndStatus, arg.AgentTaskID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanTask{}
	for rows.Next() {
		var i KanbanTask
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.AgentTaskID,
			&i.Status,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKanbanTasksByStatus = `-- name: ListKanbanTasksByStatus :many
SELECT id, title, description, agent_task_id, status, result, created_at, updated_at FROM kanban_tasks
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) ListKanbanTasksByStatus(ctx context.Context, status KanbanTaskStatus) ([]KanbanTask, error) {
	rows, err := q.db.Query(ctx, listKanbanTasksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanTask{}
	for rows.Next() {
		var i KanbanTask
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.AgentTaskID,
			&i.Status,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingKanbanTasksByAgentID = `-- name: ListPendingKanbanTasksByAgentID :many
SELECT id, title, description, agent_task_id, status, result, created_at, updated_at FROM kanban_tasks
WHERE agent_task_id = $1 AND status IN ('todo', 'progress')
ORDER BY created_at ASC
`

func (q *Queries) ListPendingKanbanTasksByAgentID(ctx context.Context, agentTaskID uuid.UUID) ([]KanbanTask, error) {
	rows, err := q.db.Query(ctx, listPendingKanbanTasksByAgentID, agentTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanTask{}
	for rows.Next() {
		var i KanbanTask
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.AgentTaskID,
			&i.Status,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetInProgressKanbanTasks = `-- name: ResetInProgressKanbanTasks :exec
UPDATE kanban_tasks SET status = 'todo', updated_at = now() WHERE status = 'progress'
`

func (q *Queries) ResetInProgressKanbanTasks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetInProgressKanbanTasks)
	return err
}

const updateKanbanTask = `-- name: UpdateKanbanTask :one
UPDATE kanban_tasks
SET title = $2,
    description = $3,
    agent_task_id = $4,
    status = $5,
    result = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, title, description, agent_task_id, status, result, created_at, updated_at
`

type UpdateKanbanTaskParams struct {
	ID          uuid.UUID        `json:"id"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	AgentTaskID uuid.UUID        `json:"agent_task_id"`
	Status      KanbanTaskStatus `json:"status"`
	Result      pgtype.Text      `json:"result"`
}

func (q *Queries) UpdateKanbanTask(ctx context.Context, arg UpdateKanbanTaskParams) (KanbanTask, error) {
	row := q.db.QueryRow(ctx, updateKanbanTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AgentTaskID,
		arg.Status,
		arg.Result,
	)
	var i KanbanTask
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AgentTaskID,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateKanbanTaskStatus = `-- name: UpdateKanbanTaskStatus :one
UPDATE kanban_tasks
SET status = $2,
    result = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, title, description, agent_task_id, status, result, created_at, updated_at
`

type UpdateKanbanTaskStatusParams struct {
	ID     uuid.UUID        `json:"id"`
	Status KanbanTaskStatus `json:"status"`
	Result pgtype.Text      `json:"result"`
}

func (q *Queries) UpdateKanbanTaskStatus(ctx context.Context, arg UpdateKanbanTaskStatusParams) (KanbanTask, error) {
	row := q.db.QueryRow(ctx, updateKanbanTaskStatus, arg.ID, arg.Status, arg.Result)
	var i KanbanTask
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AgentTaskID,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
