// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kanban_tasks.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createKanbanTask = `-- name: CreateKanbanTask :one
INSERT INTO kanban_tasks (id, title, description, agent_task_id)
VALUES (?, ?, ?, ?)
RETURNING id, title, description, agent_task_id, status, result, created_at, updated_at
`

type CreateKanbanTaskParams struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	AgentTaskID string `json:"agent_task_id"`
}

func (q *Queries) CreateKanbanTask(ctx context.Context, arg CreateKanbanTaskParams) (KanbanTask, error) {
	row := q.db.QueryRowContext(ctx, createKanbanTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AgentTaskID,
	)
	var i KanbanTask
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AgentTaskID,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKanbanTask = `-- name: DeleteKanbanTask :exec
DELETE FROM kanban_tasks WHERE id = ?
`

func (q *Queries) DeleteKanbanTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteKanbanTask, id)
	return err
}

const getKanbanTask = `-- name: GetKanbanTask :one
SELECT id, title, description, agent_task_id, status, result, created_at, updated_at FROM kanban_tasks WHERE id = ?
`

func (q *Queries) GetKanbanTask(ctx context.Context, id string) (KanbanTask, error) {
	row := q.db.QueryRowContext(ctx, getKanbanTask, id)
	var i KanbanTask
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AgentTaskID,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDistinctAgentsWithPendingKanbanTasks = `-- name: ListDistinctAgentsWithPendingKanbanTasks :many
SELECT DISTINCT agent_task_id FROM kanban_tasks
WHERE status IN ('todo', 'progress')
`

func (q *Queries) ListDistinctAgentsWithPendingKanbanTasks(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctAgentsWithPendingKanbanTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var agent_task_id string
		if err := rows.Scan(&agent_task_id); err != nil {
			return nil, err
		}
		items = append(items, agent_task_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKanbanTasks = `-- name: ListKanbanTasks :many
SELECT id, title, description, agent_task_id, status, result, created_at, updated_at FROM kanban_tasks
ORDER BY created_at DESC
`

func (q *Queries) ListKanbanTasks(ctx context.Context) ([]KanbanTask, error) {
	rows, err := q.db.QueryContext(ctx, listKanbanTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanTask{}
	for rows.Next() {
		var i KanbanTask
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.AgentTaskID,
			&i.Status,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKanbanTasksByAgentID = `-- name: ListKanbanTasksByAgentID :many
SELECT id, title, description, agent_task_id, status, result, created_at, updated_at FROM kanban_tasks
WHERE agent_task_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListKanbanTasksByAgentID(ctx context.Context, agentTaskID string) ([]KanbanTask, error) {
	rows, err := q.db.QueryContext(ctx, listKanbanTasksByAgentID, agentTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanTask{}
	for rows.Next() {
		var i KanbanTask
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.AgentTaskID,
			&i.Status,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKanbanTasksByAgentIDAndStatus = `-- name: ListKanbanTasksByAgentIDAndStatus :many
SELECT id, title, description, agent_task_id, status, result, created_at, updated_at FROM kanban_tasks
WHERE agent_task_id = ? AND status = ?
ORDER BY created_at DESC
`

type ListKanbanTasksByAgentIDAndStatusParams struct {
	AgentTaskID string `json:"agent_task_id"`
	Status      string `json:"status"`
}

func (q *Queries) ListKanbanTasksByAgentIDAndStatus(ctx context.Context, arg ListKanbanTasksByAgentIDAndStatusParams) ([]KanbanTask, error) {
	rows, err := q.db.QueryContext(ctx, listKanbanTasksByAgentIDAndStatus, arg.AgentTaskID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanTask{}
	for rows.Next() {
		var i KanbanTask
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.AgentTaskID,
			&i.Status,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKanbanTasksByStatus = `-- name: ListKanbanTasksByStatus :many
SELECT id, title, description, agent_task_id, status, result, created_at, updated_at FROM kanban_tasks
WHERE status = ?
ORDER BY created_at DESC
`

func (q *Queries) ListKanbanTasksByStatus(ctx context.Context, status string) ([]KanbanTask, error) {
	rows, err := q.db.QueryContext(ctx, listKanbanTasksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanTask{}
	for rows.Next() {
		var i KanbanTask
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.AgentTaskID,
			&i.Status,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKanbanTasksByTeamID = `-- name: ListKanbanTasksByTeamID :many
SELECT kt.id, kt.title, kt.description, kt.agent_task_id, kt.status, kt.result, kt.created_at, kt.updated_at FROM kanban_tasks kt
JOIN agent_tasks at ON kt.agent_task_id = at.id
WHERE at.team_id = ?
ORDER BY kt.created_at DESC
`

func (q *Queries) ListKanbanTasksByTeamID(ctx context.Context, teamID sql.NullString) ([]KanbanTask, error) {
	rows, err := q.db.QueryContext(ctx, listKanbanTasksByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanTask{}
	for rows.Next() {
		var i KanbanTask
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.AgentTaskID,
			&i.Status,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingKanbanTasksByAgentID = `-- name: ListPendingKanbanTasksByAgentID :many
SELECT id, title, description, agent_task_id, status, result, created_at, updated_at FROM kanban_tasks
WHERE agent_task_id = ? AND status IN ('todo', 'progress')
ORDER BY created_at ASC
`

func (q *Queries) ListPendingKanbanTasksByAgentID(ctx context.Context, agentTaskID string) ([]KanbanTask, error) {
	rows, err := q.db.QueryContext(ctx, listPendingKanbanTasksByAgentID, agentTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KanbanTask{}
	for rows.Next() {
		var i KanbanTask
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.AgentTaskID,
			&i.Status,
			&i.Result,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetInProgressKanbanTasks = `-- name: ResetInProgressKanbanTasks :exec
UPDATE kanban_tasks SET status = 'todo', updated_at = datetime('now') WHERE status = 'progress'
`

func (q *Queries) ResetInProgressKanbanTasks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetInProgressKanbanTasks)
	return err
}

const updateKanbanTask = `-- name: UpdateKanbanTask :one
UPDATE kanban_tasks
SET title = ?,
    description = ?,
    agent_task_id = ?,
    status = ?,
    result = ?,
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, title, description, agent_task_id, status, result, created_at, updated_at
`

type UpdateKanbanTaskParams struct {
	Title       string         `json:"title"`
	Description string         `json:"description"`
	AgentTaskID string         `json:"agent_task_id"`
	Status      string         `json:"status"`
	Result      sql.NullString `json:"result"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateKanbanTask(ctx context.Context, arg UpdateKanbanTaskParams) (KanbanTask, error) {
	row := q.db.QueryRowContext(ctx, updateKanbanTask,
		arg.Title,
		arg.Description,
		arg.AgentTaskID,
		arg.Status,
		arg.Result,
		arg.ID,
	)
	var i KanbanTask
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AgentTaskID,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateKanbanTaskStatus = `-- name: UpdateKanbanTaskStatus :one
UPDATE kanban_tasks
SET status = ?,
    result = ?,
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, title, description, agent_task_id, status, result, created_at, updated_at
`

type UpdateKanbanTaskStatusParams struct {
	Status string         `json:"status"`
	Result sql.NullString `json:"result"`
	ID     string         `json:"id"`
}

func (q *Queries) UpdateKanbanTaskStatus(ctx context.Context, arg UpdateKanbanTaskStatusParams) (KanbanTask, error) {
	row := q.db.QueryRowContext(ctx, updateKanbanTaskStatus, arg.Status, arg.Result, arg.ID)
	var i KanbanTask
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AgentTaskID,
		&i.Status,
		&i.Result,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
