// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"time"
)

type AgentSkill struct {
	AgentTaskID string `json:"agent_task_id"`
	SkillID     string `json:"skill_id"`
}

type AgentTask struct {
	ID                string         `json:"id"`
	Name              string         `json:"name"`
	CronExpression    sql.NullString `json:"cron_expression"`
	Prompt            string         `json:"prompt"`
	Enabled           bool           `json:"enabled"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	TaskType          string         `json:"task_type"`
	RunAt             sql.NullTime   `json:"run_at"`
	McpConfig         sql.NullString `json:"mcp_config"`
	AllowedTools      sql.NullString `json:"allowed_tools"`
	SystemAgent       bool           `json:"system_agent"`
	GlobalSkillAccess bool           `json:"global_skill_access"`
	OnSuccessTaskID   sql.NullString `json:"on_success_task_id"`
	OnFailureTaskID   sql.NullString `json:"on_failure_task_id"`
	TeamID            sql.NullString `json:"team_id"`
}

type KanbanTask struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	AgentTaskID string         `json:"agent_task_id"`
	Status      string         `json:"status"`
	Result      sql.NullString `json:"result"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Skill struct {
	ID                 string         `json:"id"`
	Title              string         `json:"title"`
	Content            string         `json:"content"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	EnvironmentSecrets sql.NullString `json:"environment_secrets"`
}

type TaskExecution struct {
	ID                     string         `json:"id"`
	AgentTaskID            sql.NullString `json:"agent_task_id"`
	Status                 string         `json:"status"`
	StartedAt              sql.NullTime   `json:"started_at"`
	FinishedAt             sql.NullTime   `json:"finished_at"`
	Summary                sql.NullString `json:"summary"`
	Error                  sql.NullString `json:"error"`
	CreatedAt              time.Time      `json:"created_at"`
	TaskName               sql.NullString `json:"task_name"`
	TriggeredByExecutionID sql.NullString `json:"triggered_by_execution_id"`
}

type Team struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Color       string    `json:"color"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
