// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skills.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const addAgentSkill = `-- name: AddAgentSkill :exec
INSERT INTO agent_skills (agent_task_id, skill_id)
VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type AddAgentSkillParams struct {
	AgentTaskID string `json:"agent_task_id"`
	SkillID     string `json:"skill_id"`
}

func (q *Queries) AddAgentSkill(ctx context.Context, arg AddAgentSkillParams) error {
	_, err := q.db.ExecContext(ctx, addAgentSkill, arg.AgentTaskID, arg.SkillID)
	return err
}

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (id, title, content, environment_secrets)
VALUES (?, ?, ?, ?)
RETURNING id, title, content, created_at, updated_at, environment_secrets
`

type CreateSkillParams struct {
	ID                 string         `json:"id"`
	Title              string         `json:"title"`
	Content            string         `json:"content"`
	EnvironmentSecrets sql.NullString `json:"environment_secrets"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRowContext(ctx, createSkill,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.EnvironmentSecrets,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnvironmentSecrets,
	)
	return i, err
}

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM skills WHERE id = ?
`

func (q *Queries) DeleteSkill(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSkill, id)
	return err
}

const getSkill = `-- name: GetSkill :one
SELECT id, title, content, created_at, updated_at, environment_secrets FROM skills WHERE id = ?
`

func (q *Queries) GetSkill(ctx context.Context, id string) (Skill, error) {
	row := q.db.QueryRowContext(ctx, getSkill, id)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnvironmentSecrets,
	)
	return i, err
}

const listSkills = `-- name: ListSkills :many
SELECT id, title, content, created_at, updated_at, environment_secrets FROM skills ORDER BY created_at DESC
`

func (q *Queries) ListSkills(ctx context.Context) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, listSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnvironmentSecrets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillsByAgentTaskID = `-- name: ListSkillsByAgentTaskID :many
SELECT s.id, s.title, s.content, s.created_at, s.updated_at, s.environment_secrets FROM skills s
JOIN agent_skills asj ON s.id = asj.skill_id
WHERE asj.agent_task_id = ?
ORDER BY s.title
`

func (q *Queries) ListSkillsByAgentTaskID(ctx context.Context, agentTaskID string) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, listSkillsByAgentTaskID, agentTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnvironmentSecrets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAgentSkill = `-- name: RemoveAgentSkill :exec
DELETE FROM agent_skills
WHERE agent_task_id = ? AND skill_id = ?
`

type RemoveAgentSkillParams struct {
	AgentTaskID string `json:"agent_task_id"`
	SkillID     string `json:"skill_id"`
}

func (q *Queries) RemoveAgentSkill(ctx context.Context, arg RemoveAgentSkillParams) error {
	_, err := q.db.ExecContext(ctx, removeAgentSkill, arg.AgentTaskID, arg.SkillID)
	return err
}

const updateSkill = `-- name: UpdateSkill :one
UPDATE skills
SET title = ?,
    content = ?,
    environment_secrets = ?,
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, title, content, created_at, updated_at, environment_secrets
`

type UpdateSkillParams struct {
	Title              string         `json:"title"`
	Content            string         `json:"content"`
	EnvironmentSecrets sql.NullString `json:"environment_secrets"`
	ID                 string         `json:"id"`
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error) {
	row := q.db.QueryRowContext(ctx, updateSkill,
		arg.Title,
		arg.Content,
		arg.EnvironmentSecrets,
		arg.ID,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnvironmentSecrets,
	)
	return i, err
}
