// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skills.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const addAgentSkill = `-- name: AddAgentSkill :exec
INSERT INTO agent_skills (agent_task_id, skill_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddAgentSkillParams struct {
	AgentTaskID uuid.UUID `json:"agent_task_id"`
	SkillID     uuid.UUID `json:"skill_id"`
}

func (q *Queries) AddAgentSkill(ctx context.Context, arg AddAgentSkillParams) error {
	_, err := q.db.Exec(ctx, addAgentSkill, arg.AgentTaskID, arg.SkillID)
	return err
}

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (title, content)
VALUES ($1, $2)
RETURNING id, title, content, created_at, updated_at
`

type CreateSkillParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill, arg.Title, arg.Content)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM skills WHERE id = $1
`

func (q *Queries) DeleteSkill(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSkill, id)
	return err
}

const getSkill = `-- name: GetSkill :one
SELECT id, title, content, created_at, updated_at FROM skills WHERE id = $1
`

func (q *Queries) GetSkill(ctx context.Context, id uuid.UUID) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkill, id)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSkills = `-- name: ListSkills :many
SELECT id, title, content, created_at, updated_at FROM skills ORDER BY created_at DESC
`

func (q *Queries) ListSkills(ctx context.Context) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillsByAgentTaskID = `-- name: ListSkillsByAgentTaskID :many
SELECT s.id, s.title, s.content, s.created_at, s.updated_at FROM skills s
JOIN agent_skills asj ON s.id = asj.skill_id
WHERE asj.agent_task_id = $1
ORDER BY s.title
`

func (q *Queries) ListSkillsByAgentTaskID(ctx context.Context, agentTaskID uuid.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkillsByAgentTaskID, agentTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAgentSkill = `-- name: RemoveAgentSkill :exec
DELETE FROM agent_skills
WHERE agent_task_id = $1 AND skill_id = $2
`

type RemoveAgentSkillParams struct {
	AgentTaskID uuid.UUID `json:"agent_task_id"`
	SkillID     uuid.UUID `json:"skill_id"`
}

func (q *Queries) RemoveAgentSkill(ctx context.Context, arg RemoveAgentSkillParams) error {
	_, err := q.db.Exec(ctx, removeAgentSkill, arg.AgentTaskID, arg.SkillID)
	return err
}

const updateSkill = `-- name: UpdateSkill :one
UPDATE skills
SET title = $2,
    content = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, title, content, created_at, updated_at
`

type UpdateSkillParams struct {
	ID      uuid.UUID `json:"id"`
	Title   string    `json:"title"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, updateSkill, arg.ID, arg.Title, arg.Content)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
