// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_executions.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const createTaskExecution = `-- name: CreateTaskExecution :one
INSERT INTO task_executions (id, agent_task_id, status, task_name, triggered_by_execution_id)
VALUES (?, ?, ?, ?, ?)
RETURNING id, agent_task_id, status, started_at, finished_at, summary, error, created_at, task_name, triggered_by_execution_id
`

type CreateTaskExecutionParams struct {
	ID                     string         `json:"id"`
	AgentTaskID            sql.NullString `json:"agent_task_id"`
	Status                 string         `json:"status"`
	TaskName               sql.NullString `json:"task_name"`
	TriggeredByExecutionID sql.NullString `json:"triggered_by_execution_id"`
}

func (q *Queries) CreateTaskExecution(ctx context.Context, arg CreateTaskExecutionParams) (TaskExecution, error) {
	row := q.db.QueryRowContext(ctx, createTaskExecution,
		arg.ID,
		arg.AgentTaskID,
		arg.Status,
		arg.TaskName,
		arg.TriggeredByExecutionID,
	)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.AgentTaskID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.TaskName,
		&i.TriggeredByExecutionID,
	)
	return i, err
}

const deleteExecutionsOlderThan = `-- name: DeleteExecutionsOlderThan :execrows
DELETE FROM task_executions
WHERE created_at < ?
`

func (q *Queries) DeleteExecutionsOlderThan(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExecutionsOlderThan, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLatestExecutionByAgentTaskID = `-- name: GetLatestExecutionByAgentTaskID :one
SELECT id, agent_task_id, status, started_at, finished_at, summary, error, created_at, task_name, triggered_by_execution_id FROM task_executions
WHERE agent_task_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestExecutionByAgentTaskID(ctx context.Context, agentTaskID sql.NullString) (TaskExecution, error) {
	row := q.db.QueryRowContext(ctx, getLatestExecutionByAgentTaskID, agentTaskID)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.AgentTaskID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.TaskName,
		&i.TriggeredByExecutionID,
	)
	return i, err
}

const getTaskExecution = `-- name: GetTaskExecution :one
SELECT id, agent_task_id, status, started_at, finished_at, summary, error, created_at, task_name, triggered_by_execution_id FROM task_executions WHERE id = ?
`

func (q *Queries) GetTaskExecution(ctx context.Context, id string) (TaskExecution, error) {
	row := q.db.QueryRowContext(ctx, getTaskExecution, id)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.AgentTaskID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.TaskName,
		&i.TriggeredByExecutionID,
	)
	return i, err
}

const listStaleRunningExecutions = `-- name: ListStaleRunningExecutions :many
SELECT id, agent_task_id, status, started_at, finished_at, summary, error, created_at, task_name, triggered_by_execution_id FROM task_executions
WHERE status = 'running'
AND started_at < ?
`

func (q *Queries) ListStaleRunningExecutions(ctx context.Context, startedAt sql.NullTime) ([]TaskExecution, error) {
	rows, err := q.db.QueryContext(ctx, listStaleRunningExecutions, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskExecution{}
	for rows.Next() {
		var i TaskExecution
		if err := rows.Scan(
			&i.ID,
			&i.AgentTaskID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.TaskName,
			&i.TriggeredByExecutionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskExecutions = `-- name: ListTaskExecutions :many
SELECT id, agent_task_id, status, started_at, finished_at, summary, error, created_at, task_name, triggered_by_execution_id FROM task_executions
ORDER BY created_at DESC
`

func (q *Queries) ListTaskExecutions(ctx context.Context) ([]TaskExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTaskExecutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskExecution{}
	for rows.Next() {
		var i TaskExecution
		if err := rows.Scan(
			&i.ID,
			&i.AgentTaskID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.TaskName,
			&i.TriggeredByExecutionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskExecutionsByAgentTaskID = `-- name: ListTaskExecutionsByAgentTaskID :many
SELECT id, agent_task_id, status, started_at, finished_at, summary, error, created_at, task_name, triggered_by_execution_id FROM task_executions
WHERE agent_task_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListTaskExecutionsByAgentTaskID(ctx context.Context, agentTaskID sql.NullString) ([]TaskExecution, error) {
	rows, err := q.db.QueryContext(ctx, listTaskExecutionsByAgentTaskID, agentTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskExecution{}
	for rows.Next() {
		var i TaskExecution
		if err := rows.Scan(
			&i.ID,
			&i.AgentTaskID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.TaskName,
			&i.TriggeredByExecutionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskExecutionStatus = `-- name: UpdateTaskExecutionStatus :one
UPDATE task_executions
SET status = ?,
    started_at = ?,
    finished_at = ?,
    summary = ?,
    error = ?
WHERE id = ?
RETURNING id, agent_task_id, status, started_at, finished_at, summary, error, created_at, task_name, triggered_by_execution_id
`

type UpdateTaskExecutionStatusParams struct {
	Status     string         `json:"status"`
	StartedAt  sql.NullTime   `json:"started_at"`
	FinishedAt sql.NullTime   `json:"finished_at"`
	Summary    sql.NullString `json:"summary"`
	Error      sql.NullString `json:"error"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateTaskExecutionStatus(ctx context.Context, arg UpdateTaskExecutionStatusParams) (TaskExecution, error) {
	row := q.db.QueryRowContext(ctx, updateTaskExecutionStatus,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Summary,
		arg.Error,
		arg.ID,
	)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.AgentTaskID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.TaskName,
		&i.TriggeredByExecutionID,
	)
	return i, err
}
