// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_executions.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTaskExecution = `-- name: CreateTaskExecution :one
INSERT INTO task_executions (agent_task_id, status, task_name, triggered_by_execution_id)
VALUES ($1, $2, $3, $4)
RETURNING id, agent_task_id, status, started_at, finished_at, summary, error, created_at, task_name, triggered_by_execution_id
`

type CreateTaskExecutionParams struct {
	AgentTaskID            pgtype.UUID     `json:"agent_task_id"`
	Status                 ExecutionStatus `json:"status"`
	TaskName               pgtype.Text     `json:"task_name"`
	TriggeredByExecutionID pgtype.UUID     `json:"triggered_by_execution_id"`
}

func (q *Queries) CreateTaskExecution(ctx context.Context, arg CreateTaskExecutionParams) (TaskExecution, error) {
	row := q.db.QueryRow(ctx, createTaskExecution,
		arg.AgentTaskID,
		arg.Status,
		arg.TaskName,
		arg.TriggeredByExecutionID,
	)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.AgentTaskID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.TaskName,
		&i.TriggeredByExecutionID,
	)
	return i, err
}

const deleteExecutionsOlderThan = `-- name: DeleteExecutionsOlderThan :execrows
DELETE FROM task_executions
WHERE created_at < $1
`

func (q *Queries) DeleteExecutionsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExecutionsOlderThan, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLatestExecutionByAgentTaskID = `-- name: GetLatestExecutionByAgentTaskID :one
SELECT id, agent_task_id, status, started_at, finished_at, summary, error, created_at, task_name, triggered_by_execution_id FROM task_executions
WHERE agent_task_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestExecutionByAgentTaskID(ctx context.Context, agentTaskID pgtype.UUID) (TaskExecution, error) {
	row := q.db.QueryRow(ctx, getLatestExecutionByAgentTaskID, agentTaskID)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.AgentTaskID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.TaskName,
		&i.TriggeredByExecutionID,
	)
	return i, err
}

const getTaskExecution = `-- name: GetTaskExecution :one
SELECT id, agent_task_id, status, started_at, finished_at, summary, error, created_at, task_name, triggered_by_execution_id FROM task_executions WHERE id = $1
`

func (q *Queries) GetTaskExecution(ctx context.Context, id uuid.UUID) (TaskExecution, error) {
	row := q.db.QueryRow(ctx, getTaskExecution, id)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.AgentTaskID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.TaskName,
		&i.TriggeredByExecutionID,
	)
	return i, err
}

const listStaleRunningExecutions = `-- name: ListStaleRunningExecutions :many
SELECT id, agent_task_id, status, started_at, finished_at, summary, error, created_at, task_name, triggered_by_execution_id FROM task_executions
WHERE status = 'running'
AND started_at < $1
`

func (q *Queries) ListStaleRunningExecutions(ctx context.Context, startedAt pgtype.Timestamptz) ([]TaskExecution, error) {
	rows, err := q.db.Query(ctx, listStaleRunningExecutions, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskExecution{}
	for rows.Next() {
		var i TaskExecution
		if err := rows.Scan(
			&i.ID,
			&i.AgentTaskID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.TaskName,
			&i.TriggeredByExecutionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskExecutions = `-- name: ListTaskExecutions :many
SELECT id, agent_task_id, status, started_at, finished_at, summary, error, created_at, task_name, triggered_by_execution_id FROM task_executions
ORDER BY created_at DESC
`

func (q *Queries) ListTaskExecutions(ctx context.Context) ([]TaskExecution, error) {
	rows, err := q.db.Query(ctx, listTaskExecutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskExecution{}
	for rows.Next() {
		var i TaskExecution
		if err := rows.Scan(
			&i.ID,
			&i.AgentTaskID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.TaskName,
			&i.TriggeredByExecutionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskExecutionsByAgentTaskID = `-- name: ListTaskExecutionsByAgentTaskID :many
SELECT id, agent_task_id, status, started_at, finished_at, summary, error, created_at, task_name, triggered_by_execution_id FROM task_executions
WHERE agent_task_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTaskExecutionsByAgentTaskID(ctx context.Context, agentTaskID pgtype.UUID) ([]TaskExecution, error) {
	rows, err := q.db.Query(ctx, listTaskExecutionsByAgentTaskID, agentTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskExecution{}
	for rows.Next() {
		var i TaskExecution
		if err := rows.Scan(
			&i.ID,
			&i.AgentTaskID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Summary,
			&i.Error,
			&i.CreatedAt,
			&i.TaskName,
			&i.TriggeredByExecutionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskExecutionStatus = `-- name: UpdateTaskExecutionStatus :one
UPDATE task_executions
SET status = $2,
    started_at = $3,
    finished_at = $4,
    summary = $5,
    error = $6
WHERE id = $1
RETURNING id, agent_task_id, status, started_at, finished_at, summary, error, created_at, task_name, triggered_by_execution_id
`

type UpdateTaskExecutionStatusParams struct {
	ID         uuid.UUID          `json:"id"`
	Status     ExecutionStatus    `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Summary    pgtype.Text        `json:"summary"`
	Error      pgtype.Text        `json:"error"`
}

func (q *Queries) UpdateTaskExecutionStatus(ctx context.Context, arg UpdateTaskExecutionStatusParams) (TaskExecution, error) {
	row := q.db.QueryRow(ctx, updateTaskExecutionStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Summary,
		arg.Error,
	)
	var i TaskExecution
	err := row.Scan(
		&i.ID,
		&i.AgentTaskID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Summary,
		&i.Error,
		&i.CreatedAt,
		&i.TaskName,
		&i.TriggeredByExecutionID,
	)
	return i, err
}
